INSERT INTO __KEYSPACE__.measurement_by_device_day
(device_id, day, measured_at, variable, value, unit, quality)
VALUES ('AIR-002', '2025-05-12', '2025-05-12T10:32:00Z', 'co2', 812, 'ppm', 'GOOD');
INSERT INTO __KEYSPACE__.measurement_by_device_day
(device_id, day, measured_at, variable, value, unit, quality)
VALUES ('AIR-002', '2025-05-12', '2025-05-12T10:32:00Z', 'temperature', 24.6, 'C', 'GOOD');
INSERT INTO __KEYSPACE__.measurement_by_device_day
(device_id, day, measured_at, variable, value, unit, quality)
VALUES ('AIR-002', '2025-05-12', '2025-05-12T10:31:30Z', 'co2', 806, 'ppm', 'GOOD');
INSERT INTO __KEYSPACE__.measurement_by_device_day
(device_id, day, measured_at, variable, value, unit, quality)
VALUES ('AIR-002', '2025-05-12', '2025-05-12T10:31:30Z', 'humidity', 47.8, 'percent', 'GOOD');
INSERT INTO __KEYSPACE__.measurement_by_device_day
(device_id, day, measured_at, variable, value, unit, quality)
VALUES ('AIR-002', '2025-05-12', '2025-05-12T10:31:00Z', 'co2', 799, 'ppm', 'GOOD');
INSERT INTO __KEYSPACE__.measurement_by_device_day
(device_id, day, measured_at, variable, value, unit, quality)
VALUES ('AMB-001', '2025-05-12', '2025-05-12T10:32:00Z', 'temperature', 24.6, 'C', 'GOOD');
INSERT INTO __KEYSPACE__.measurement_by_device_day
(device_id, day, measured_at, variable, value, unit, quality)
VALUES ('AMB-001', '2025-05-12', '2025-05-12T10:32:00Z', 'humidity', 48.2, 'percent', 'GOOD');
INSERT INTO __KEYSPACE__.measurement_by_device_day
(device_id, day, measured_at, variable, value, unit, quality)
VALUES ('ACT-003', '2025-05-12', '2025-05-12T10:32:00Z', 'ventilation_state', 0, 'boolean', 'GOOD');
